apiVersion: v1
kind: Service
metadata:
  name: guesttracker
  namespace: hackerspace
  labels:
    app: guesttracker
spec:
  type: LoadBalancer 
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: guesttracker